name: HaraxxCore
version: 1.1.8
main: net.haraxx.coresystem.CoreSystem
api-version: 1.18
authors: [ Sakubami, Gold.ly ]
description: CoreSystem for the Haraxx Network, Copyright Haraxx 2023 (C)
website: Haraxx.net

commands:
  core:
    description: core command