name: HaraxxCore
version: 1.4.3
main: net.haraxx.coresystem.CoreSystem
api-version: 1.18
authors: [ sakubami, Gero ]
description: CoreSystem for the Haraxx Network, Copyright Haraxx 2023 (C)
website: Haraxx.net
depend:
  - LuckPerms

commands:
  haraxx:
    description: core command
    aliases:
      - hc
      - hcore
  spawn:
    description: sends player to spawn