name: HaraxxCore
version: 1.1.2
main: net.haraxx.coresystem.CoreSystem
api-version: 1.18
authors: [ Sakubami, Gold.ly ]
description: RPG-CoreSystem for the Haraxx Server, Copyright Haraxx 2023 (C)
website: Haraxx.net

commands:
  core:
    description: core command