name: HaraxxCore
version: '${project.version}'
main: net.haraxx.coresystem.CoreSystem
api-version: 1.18
authors: [ sakubami, Gero ]
description: CoreSystem for the Haraxx Network, Copyright Haraxx 2023 (C)
website: Haraxx.net
softdepend:
  - LuckPerms
  - Multiverse-Core

commands:
  haraxx:
    description: core command
    aliases:
      - hc
      - hcore
  spawn:
    description: sends player to spawn